#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

sh $SCRIPTPATH/.xrandr.sh
sh $SCRIPTPATH/xrandr-Alt.sh
sh $SCRIPTPATH/autostart.sh


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#1) set background for all displays
#if [ -x "$(command -v feh)" ]; then
#  feh --bg-scale $SCRIPTPATH/background.jpg
#fi

# 2) START - set MULTIPLE wallpapers for all displays ----------------------+
# NOTE: the last image path DO NOT end with "\"
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill \
  "$SCRIPTPATH"/wallpapers/wall-monA-1.png\
  "$SCRIPTPATH"/wallpapers/wall-monB-1.png
fi
# END ----------------------------------------------------------------------+

index=0
monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  let indextemp=index+1
  monitor=$(sed "$indextemp!d" <<<"$monitors")
  barname="mainbar$index"
  monitor=$monitor offset=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=indextemp
done

